### ISSUE TITLE
add as friend doesnt work

### ISSUE THREAD

**Issue by pumpkinwitch** [katjalennartz/socialnetwork_2.0#11]
after switching to PHP8 blank page (HTTP 500 error) occurs when you try to add someone as a friend (for example: "/member.php?action=profile&uid=6&area=socialnetwork&friend=plus&friendid=6"), removing friends works as it should!

**Comment by katjalennartz** [comment]
thanks for the info. I'll have a look :)

**Comment by katjalennartz** [comment]
Hey @pumpkinwitch 
i tried to reproduce the error, but it's working fine on php 8.2 locally. do you have the newest version of the plugin? 
Which browser are you using?
perhaps the error comes from the alert, wich type of alert did you set (pm or myalerts?) 

I found one error, when using pm as alert type. I updated the inc/plugin file. But not sure, if it's the same issue you had. So perhaps you can give me some short feedback?

**Comment by pumpkinwitch** [comment]
hey sorry for taking so long, your fix worked already! Thank you so much

**Comment by pumpkinwitch** [comment]
sadly we have a new issue now. tryin to open someones profile ("/member.php?action=profile&uid=XX") leads to the same blank page, only happens with those who use the social network. 
still using pm alerts only on chrome

**Comment by katjalennartz** [comment]
omg. this was totally my fault. i've forgot i added some extras for my own forum, like a new db field etc. Of course this crashed the plugin :D 
I've optimized some things, updated the readme file and add an update script for adding the new field and templates. 
Pls make sure to upload all the new/updates files (update script,adding templates file, language files etc.) and after upload them do the update script and everything should work again. <3

**Comment by pumpkinwitch** [comment]
Yes works perfectly now!
Thank you again <3
